# Generated by Django 5.2.12 on 2026-03-31 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer_choice',
            name='question',
        ),
        migrations.RemoveField(
            model_name='quiz_question',
            name='correct_answer',
        ),
        migrations.AddField(
            model_name='quiz_question',
            name='choices',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_question', to='quiz.answer_choice'),
        ),
    ]
