# Generated by Django 5.2.12 on 2026-03-31 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_remove_answer_choice_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz_question',
            name='choices',
        ),
        migrations.AddField(
            model_name='answer_choice',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answer_choice',
            name='question',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='quiz.quiz_question'),
            preserve_default=False,
        ),
    ]
