# Generated by Django 5.2.12 on 2026-04-08 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_remove_quiz_question_choices_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer_choice',
            options={'ordering': ('order', 'id')},
        ),
        migrations.AlterModelOptions(
            name='answersubmission',
            options={'ordering': ('-submitted_at',)},
        ),
        migrations.AlterModelOptions(
            name='quiz_question',
            options={'ordering': ('order', 'id')},
        ),
        migrations.AddField(
            model_name='quiz_instance',
            name='code',
            field=models.CharField(default='000000', max_length=6),
            preserve_default=False,
        ),
    ]
